microcontroller:
  idmcu: 3 # id of mcu 
  namespace: "subsys3" # namespace
  generate_library_Path: "Arduino"  # path for generate library
  connection:
    type: "UART"   # ["UART","UDP"] 
    
    serial_port: "/dev/ttyACM0"  # for Serial UART Subsystem 2"
    baudrate: 57620  # for UART
    ip_address_mcu: ""  # for UDP example "192.168.1.xx"
    udp_port_mcu: 0  # for UDP


ros: # setup ros is reference from microcontroller example publisher is mean microcontroller publish to ros network
  publisher:  [                           ]
  subscriber: [
    [1, "head_rot", "std_msgs/Int16.msg"],
    [2, "jaw", "std_msgs/Int16.msg"],
    [3, "eyey", "std_msgs/Int16.msg"],
    [4, "eyex_l", "std_msgs/Int16.msg"],
    [5, "eyex_r", "std_msgs/Int16.msg"],
    [6, "head_front", "std_msgs/Int16.msg"],
    [7, "head_rear", "std_msgs/Int16.msg"], 
  ]
  
  srv_client: [                           ]
  srv_server: [                           ]
  action_client: [                        ]
  action_server: [                        ]
